name: Build ISCAM workspace

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-rdata:
    if: ${{ github.actor != 'github-actions[bot]' }} 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools

      - run: mkdir -p docs

      - name: Generate RData workspace file
        run: |
          devtools::load_all()
          iscamdata <- ls(getNamespace("ISCAM"), all.names = TRUE)
          print(iscamdata)
          iscamdata <- c(
            iscamdata[
              !iscamdata %in%
                c(
                  ".__DEVTOOLS__",
                  ".__NAMESPACE__.",
                  ".__S3MethodsTable__.",
                  ".packageName"
                )
            ],
            Sys.glob("data/*.rda")  |> basename()  |> gsub("\\.rda$", "", x = _)
          )
          print(iscamdata)
          save(list = iscamdata, file = "docs/ISCAM.RData")
        shell: Rscript {0}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update ISCAM.RData [skip ci]"
          file_pattern: dev/ISCAM.RData